# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_description', models.CharField(blank=True, max_length=120, verbose_name='OFFENSE DESCRIPTION')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='DISTRICT')),
                ('reporting_area', models.CharField(blank=True, max_length=120, verbose_name='REPORTING AREA')),
                ('occurred_on_date', models.DateTimeField(blank=True, verbose_name='OCCURRED ON DATE')),
                ('hour', models.IntegerField(blank=True, verbose_name='HOUR')),
                ('year', models.IntegerField(blank=True, verbose_name='YEAR')),
                ('month', models.IntegerField(blank=True, verbose_name='MONTH')),
                ('day_of_week', models.CharField(blank=True, max_length=120, verbose_name='DAY OF WEEK')),
                ('ucr_part', models.CharField(blank=True, max_length=120, verbose_name='UCR PART')),
                ('street', models.CharField(blank=True, max_length=120, verbose_name='STREET')),
                ('latitude', models.FloatField(blank=True, verbose_name='LATITUDE')),
                ('longitude', models.FloatField(blank=True, verbose_name='LONGITUDE')),
            ],
        ),
    ]
