# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestRoute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedatapoint',
            name='incident_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='INCIDENT NUMBER'),
        ),
        migrations.AddField(
            model_name='crimedatapoint',
            name='offense_codd',
            field=models.IntegerField(blank=True, default=1, verbose_name='OFFENSE CODE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crimedatapoint',
            name='offense_code_group',
            field=models.CharField(blank=True, max_length=120, verbose_name='OFFENSE CODE GROUP'),
        ),
    ]
