# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestRoute', '0002_auto_20170402_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedatapoint',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='DAY OF WEEK'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='DISTRICT'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='HOUR'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='incident_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='INCIDENT NUMBER'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='LONGITUDE'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='MONTH'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='occurred_on_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OCCURRED ON DATE'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='offense_codd',
            field=models.IntegerField(blank=True, null=True, verbose_name='OFFENSE CODE'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='offense_code_group',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='OFFENSE CODE GROUP'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='offense_description',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='OFFENSE DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='reporting_area',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='REPORTING AREA'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='STREET'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='ucr_part',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='UCR PART'),
        ),
        migrations.AlterField(
            model_name='crimedatapoint',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='YEAR'),
        ),
    ]
