# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestRoute', '0003_auto_20170402_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimedatapoint',
            name='occurred_on_date',
        ),
    ]
