# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestRoute', '0004_remove_crimedatapoint_occurred_on_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedatapoint',
            name='occurred_on_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OCCURRED ON DATE'),
        ),
    ]
